# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FunnelAT0112 < Formula
  desc "distributed task execution toolkit"
  homepage "https://ohsu-comp-bio.github.io/funnel/"
  version "0.11.2"

  on_macos do
    on_intel do
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.2/funnel-darwin-amd64-0.11.2.tar.gz"
      sha256 "da610861afea661f03e99076b3be696380e47040155d4a16ea4c7fbe5eb9d2fc"

      def install
        bin.install "funnel"
      end
    end
    on_arm do
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.2/funnel-darwin-arm64-0.11.2.tar.gz"
      sha256 "229714506f7f8ce588bbc85910d1e17cc1a5f11343cf5d456864c828a3ad0fa5"

      def install
        bin.install "funnel"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.2/funnel-linux-amd64-0.11.2.tar.gz"
        sha256 "88f406e02366ec98e3f033d3f042812f37108da76671b54af773946ea6e0f791"

        def install
          bin.install "funnel"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.2/funnel-linux-arm64-0.11.2.tar.gz"
        sha256 "4625f8f9d40556bccd1915903b5e0a84071ea64d6e64fcf26467f66363be867f"

        def install
          bin.install "funnel"
        end
      end
    end
  end

  test do
    system "#{bin}/funnel", "version"
  end
end
