# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Funnel < Formula
  desc "distributed task execution toolkit"
  homepage "https://ohsu-comp-bio.github.io/funnel/"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0/funnel-darwin-arm64-0.11.0.tar.gz"
      sha256 "8b828a7a2d352732f995add38bae5a8f0c7756956a91dadff1b0222b54f228b5"

      def install
        bin.install "funnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0/funnel-darwin-amd64-0.11.0.tar.gz"
      sha256 "86da5574dda6ce65d119113eda11f798cb16512389717dcbf2637bf57a124d7e"

      def install
        bin.install "funnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0/funnel-linux-arm64-0.11.0.tar.gz"
      sha256 "20b7655c339eb6fa56a2c5397eedf5dd1228ce7dc1fc104ef4348ff681b717bc"

      def install
        bin.install "funnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0/funnel-linux-amd64-0.11.0.tar.gz"
      sha256 "4a62ff05462825e30c4b612689d066ba804dd124000aa29ab1e20c9ed9d71f84"

      def install
        bin.install "funnel"
      end
    end
  end

  test do
    system "#{bin}/funnel", "version"
  end
end
