# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Funnel < Formula
  desc "distributed task execution toolkit"
  homepage "https://ohsu-comp-bio.github.io/funnel/"
  version "0.11.0-rc.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.1/funnel-darwin-arm64-0.11.0-rc.1.tar.gz"
      sha256 "a4351a50ec4575c6a0116510221fc1cf6d4a9b77c9237f710eb519293ca6070b"

      def install
        bin.install "funnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.1/funnel-darwin-amd64-0.11.0-rc.1.tar.gz"
      sha256 "c38feae5353a5a27acd9820aafcf79d765656882e4827e4c2f267ae42307ddef"

      def install
        bin.install "funnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.1/funnel-linux-arm64-0.11.0-rc.1.tar.gz"
      sha256 "2d40146f51a937871e3c18d58176bfd7724d0eb4719c82a975dfee8a37297d3d"

      def install
        bin.install "funnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.1/funnel-linux-amd64-0.11.0-rc.1.tar.gz"
      sha256 "4891ff0c31d5dd713a4be93316a2b8265e50bce3347ff6ff7b4bd5ba212c13c6"

      def install
        bin.install "funnel"
      end
    end
  end

  test do
    system "#{bin}/funnel", "version"
  end
end
