# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Funnel < Formula
  desc "distributed task execution toolkit"
  homepage "https://ohsu-comp-bio.github.io/funnel/"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0/funnel-darwin-arm64-0.11.0.tar.gz"
      sha256 "62d988ec1fce5ed60d8860b435072fc3fb26996b23ebe791174b900e74fe6a4e"

      def install
        bin.install "funnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0/funnel-darwin-amd64-0.11.0.tar.gz"
      sha256 "e49bfed867ca9ac0f6f896815fbc2008da79f540da584b09893222afbafd63be"

      def install
        bin.install "funnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0/funnel-linux-arm64-0.11.0.tar.gz"
      sha256 "5ba4c9dd3eb7bdda78e043c5a90d8cb6709fae6950f8c4c8283ab9bb14eacd80"

      def install
        bin.install "funnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0/funnel-linux-amd64-0.11.0.tar.gz"
      sha256 "4bea00b33e4d078fb4f58f6dcf62d6f7dc4025896e40a3f5984f89bf6def6287"

      def install
        bin.install "funnel"
      end
    end
  end

  test do
    system "#{bin}/funnel", "version"
  end
end
