# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FunnelAT011 < Formula
  desc "distributed task execution toolkit"
  homepage "https://ohsu-comp-bio.github.io/funnel/"
  version "0.11.0-rc.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.4/funnel-darwin-arm64-0.11.0-rc.4.tar.gz"
      sha256 "0aef86f6ec67be57b303a5a27dee84ecb91fb7d8f950631c85a6c8a50d64af04"

      def install
        bin.install "funnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.4/funnel-darwin-amd64-0.11.0-rc.4.tar.gz"
      sha256 "32d11a3cd417be22c5bec4c9295598e6b827677cee6f72b305cc19697e727ff7"

      def install
        bin.install "funnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.4/funnel-linux-arm64-0.11.0-rc.4.tar.gz"
      sha256 "dad1f335ced09878bc493f83841f447582638d37fdd25e177dedc132b93cdd66"

      def install
        bin.install "funnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.4/funnel-linux-amd64-0.11.0-rc.4.tar.gz"
      sha256 "a8b5c8427efb419c78c77fdd498753ef5e91e8e7348c226f24f618d6854572bd"

      def install
        bin.install "funnel"
      end
    end
  end

  test do
    system "#{bin}/funnel", "version"
  end
end
