# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FunnelAT011 < Formula
  desc "distributed task execution toolkit"
  homepage "https://ohsu-comp-bio.github.io/funnel/"
  version "0.11.0-rc.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.4/funnel-darwin-arm64-0.11.0-rc.4.tar.gz"
      sha256 "12a1e9ed988c576996205f087799f461123338965a2a9110ae3b351bd55d277d"

      def install
        bin.install "funnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.4/funnel-darwin-amd64-0.11.0-rc.4.tar.gz"
      sha256 "6951e37a1e0b8cd141dd84ee44a3671d1bd33ed66f89a27109e6723c7f924616"

      def install
        bin.install "funnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.4/funnel-linux-arm64-0.11.0-rc.4.tar.gz"
      sha256 "db1768b3809561624efc18e55c4416a548fb0b34cb7b4b91eabc0235bc4a89e6"

      def install
        bin.install "funnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.0-rc.4/funnel-linux-amd64-0.11.0-rc.4.tar.gz"
      sha256 "83dc07bf0fdc59280d4b03b7aedf3185d2bed5bd33cf8475dddf979fe578782a"

      def install
        bin.install "funnel"
      end
    end
  end

  test do
    system "#{bin}/funnel", "version"
  end
end
