# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Funnel < Formula
  desc "distributed task execution toolkit"
  homepage "https://ohsu-comp-bio.github.io/funnel/"
  version "0.11.1-rc.2"

  on_macos do
    on_intel do
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.1-rc.2/funnel-darwin-amd64-0.11.1-rc.2.tar.gz"
      sha256 "55d8ee77909b15049c5b45a7382225b24ce8da60d667f3872a5ff387f42479aa"

      def install
        bin.install "funnel"
      end
    end
    on_arm do
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.1-rc.2/funnel-darwin-arm64-0.11.1-rc.2.tar.gz"
      sha256 "8a834b1676a8f280761022ba37ebfacd3c2a75a1a792cb44f95f5a3c9d8f9734"

      def install
        bin.install "funnel"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.1-rc.2/funnel-linux-amd64-0.11.1-rc.2.tar.gz"
        sha256 "ff22f5b5574d0100ace93d9875df35520593311e5b79014ed746a11da1f06733"

        def install
          bin.install "funnel"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.1-rc.2/funnel-linux-arm64-0.11.1-rc.2.tar.gz"
        sha256 "964cf877d1826b3201614594bca6204b7ae95273fac50f558c45ceb3633ca62e"

        def install
          bin.install "funnel"
        end
      end
    end
  end

  test do
    system "#{bin}/funnel", "version"
  end
end
