# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Funnel < Formula
  desc "distributed task execution toolkit"
  homepage "https://ohsu-comp-bio.github.io/funnel/"
  version "0.11.3"

  on_macos do
    on_intel do
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.3/funnel-darwin-amd64-0.11.3.tar.gz"
      sha256 "95be85ad024151b66a32822c1659efe06cc757402c8c983a1f94db29480675cc"

      def install
        bin.install "funnel"
      end
    end
    on_arm do
      url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.3/funnel-darwin-arm64-0.11.3.tar.gz"
      sha256 "966cb755f6bb39534c4cc075005d485fa8111fbeed5552252655bbb4f718cce2"

      def install
        bin.install "funnel"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.3/funnel-linux-amd64-0.11.3.tar.gz"
        sha256 "4f0fe84f28fc12672727cfc7c96b5a97dc29110b47efc62b45a754692bf3f6e0"

        def install
          bin.install "funnel"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ohsu-comp-bio/funnel/releases/download/0.11.3/funnel-linux-arm64-0.11.3.tar.gz"
        sha256 "b39bd78a167fd8162ead4c1b1a77c493dba5b42ba5d126034709cf158ba856e4"

        def install
          bin.install "funnel"
        end
      end
    end
  end

  test do
    system "#{bin}/funnel", "version"
  end
end
